name: AWS Code Whisperer Test

on:
  push:
    branches:
      - ana
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050122078:role/code_whisperer
          aws-region: us-east-1

      - name: Test deploy (örnek komut)
        run: echo "Başarılı! AWS rolü çalıştı!"
